### ISSUE TITLE
Reports where field is null

### ISSUE THREAD

**Issue by h1771t** [Simpsonpt/django-acra#4]
In some cases, android sent reports where some field (eg. user_comments) was null in the json, this causes crashreport.save() to fail because a field is defined, but is null. The model defaults to "" for undefined fields, but does not allow null values. So defined fields in the report with null values fail.

If I changed https://github.com/Simpsonpt/django-acra/blob/master/acra/views.py#L46 to
if(v!=None and json_data[key] != None)
then it solves the issue for me.

**Comment by Simpsonpt** [comment]
Hi hiren1771,

Thank you for the issue, but the all project is outdated and need several updates on the frameworks and libs. For now, the best option would be to you to do a fork and change the code to fit your needs or send a PR with that change.

I don't have a lot of free time nowadays, but when and if I plan to do an update/refactor I will fix this behavior (if not before with a PR). 

Anyway, I will not close the issue because it needs to be fixed.
